name: Check Punch Status
on:
  workflow_dispatch: # Cho phép chạy thủ công
  schedule:
    # CẬP NHẬT: Chạy lúc 00:00 UTC (7:00 Sáng VN) - Thứ Ba, Thứ Tư
    - cron: '0 0 * * 2,3'

jobs:
  check-status-and-notify:
    name: Check Status and Notify
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: 1. Check out repository
        uses: actions/checkout@v4

      - name: 2. Check Automation Status
        id: check_config
        run: |
          sudo apt-get install -y jq
          IS_ENABLED=$(jq '.isAutomationEnabled' config.json)
          echo "Automation enabled: $IS_ENABLED"
          echo "is_enabled=$IS_ENABLED" >> $GITHUB_OUTPUT

      - name: 3. Send Warning Notification if Disabled
        if: steps.check_config.outputs.is_enabled == 'false'
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}' \
          -d '{
                "cardsV2": [
                  {
                    "cardId": "reminder-card-disabled",
                    "card": {
                      "header": {
                        "title": "🚨 CẢNH BÁO: Auto-Punch Đang TẮT",
                        "subtitle": "Phát hiện lúc 7:00 AM",
                        "imageUrl": "https://i.imgur.com/A53t3zP.png",
                        "imageType": "CIRCLE"
                      },
                      "sections": [
                        {
                          "widgets": [
                            {
                              "textParagraph": {
                                "text": "Hệ thống Auto-Punch (WFH) đang ở trạng thái TẮT (Disabled).<br><br>Bạn <b>đã bị lỡ</b> lượt punch-in lúc 6:00 sáng nay.<br><br>Vui lòng <b>bật lại</b> hệ thống ngay lập tức (hoặc tự punch-in thủ công)."
                              }
                            }
                          ]
                        }
                      ]
                    }
                  }
                ]
              }'
