name: Office Check-in Reminder
on:
  workflow_dispatch: # Cho phép chạy thủ công
  schedule:
    # Chạy lúc 1:00 UTC (8:00 Sáng VN) - Thứ 2, Thứ 5, Thứ 6
    - cron: '0 1 * * 1,4,5'

jobs:
  send-reminder:
    name: Send Office Reminder
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: 1. Send Google Chat Notification
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}' \
          -d '{ "cardsV2": [ { "cardId": "reminder-card", "card": { "header": { "title": "🏢 Nhắc nhở Check-in", "subtitle": "Hôm nay là ngày lên văn phòng!", "imageUrl": "https://i.imgur.com/qS5tW0C.png", "imageType": "CIRCLE" }, "sections": [ { "widgets": [ { "textParagraph": { "text": "Đừng quên chấm công tại văn phòng nhé." } } ] } ] } } ] }'
        env:
          GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}