name: Reminder to Enable Punch
on:
  workflow_dispatch: # Cho phép chạy thủ công
  schedule:
    # Chạy lúc 13:00 UTC (20:00 Tối VN) - Thứ Hai, Thứ Ba
    - cron: '0 13 * * 1,2'

jobs:
  check-status-and-remind:
    name: Check Status and Remind
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: 1. Check out repository
        uses: actions/checkout@v4

      - name: 2. Check Automation Status
        id: check_config
        run: |
          sudo apt-get install -y jq
          IS_ENABLED=$(jq '.isAutomationEnabled' config.json)
          echo "Automation enabled: $IS_ENABLED"
          echo "is_enabled=$IS_ENABLED" >> $GITHUB_OUTPUT

      - name: 3. Send Warning Notification if Disabled
        if: steps.check_config.outputs.is_enabled == 'false' # Chỉ chạy nếu bị TẮT
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}' \
          -d '{
                "cardsV2": [
                  {
                    "cardId": "reminder-card-night",
                    "card": {
                      "header": {
                        "title": "🚨 CẢNH BÁO: Auto-Punch Đang TẮT",
                        "subtitle": "Phát hiện lúc 20:00 (8 giờ tối)",
                        "imageUrl": "https://i.imgur.com/A53t3zP.png",
                        "imageType": "CIRCLE"
                      },
                      "sections": [
                        {
                          "widgets": [
                            {
                              "textParagraph": {
                                "text": "Hệ thống Auto-Punch (WFH) đang ở trạng thái TẮT (Disabled).<br><br>Vui lòng <b>BẬT lại</b> (dùng iOS Shortcut) trước khi đi ngủ, nếu không bạn sẽ <b>bị lỡ</b> lượt punch-in lúc 6:00 sáng mai."
                              }
                            }
                          ]
                        }
                      ]
                    }
                  }
                ]
              }'
